### ISSUE TITLE
Graph Rover links do not work

### ISSUE THREAD

**Issue by berezovskyi** [dydra/support#61] opened 2020-11-25 23:43 UTC
E.g. from https://dydra.com/cldwalker/knowledge-graph-activities:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/64734/100292310-61ea5a80-2f80-11eb-9501-81204fabb862.png">

Redirects from http://apps.metreeca.it/rover/#endpoint=https://dydra.com/cldwalker/knowledge-graph-activities/sparql to https://demo.metreeca.com/apps/self/

**Comment by lisp** [comment] 2020-11-26 08:00
please be more specific.
the given link leads to a single request, which succeeds.
we know nothing about the workings of the metreeca app itself.

**Comment by berezovskyi** [comment] 2020-11-26 08:27
Could you please try from a private browser window? As you see in the screenshot above, the request doesn't succeed from the user point of view.

**Comment by berezovskyi** [comment] 2020-11-26 08:28
FF 82 on macOS, not logged in to Dydra.

**Comment by lisp** [comment] 2020-11-26 08:47
i can see that the request does not succeed from the point of view of the metreeca application.
i can see that their request to dydra does.

could you please reproduce whatever operation you believe should work in the form of a shell script with a curl request and indicate what you expect the result to be.
i have no knowledge of what the metreeca application attempting beyond the single request which it makes to the service.
as that succeeds i cannot say why the app reports a "network" failure.

**Comment by berezovskyi** [comment] 2020-11-26 09:39
Sorry, I am just a user (well, I am a developer who works with RDF but in this particular case I am wearing a user hat), not even an owner of the Dydra dataset in question. I have 0 clue about Data Rover or metreeca. I have assumed Data Rover is the functionality Dydra offers because the link to it was on the dataset's homepage. Are you saying that the Data Rover link is not part of Dydra functionality?

**Comment by berezovskyi** [comment] 2020-11-26 09:39
And thank you for checking the logs!

**Comment by berezovskyi** [comment] 2020-11-26 09:40
![image](https://user-images.githubusercontent.com/64734/100334281-dc909580-2fd3-11eb-9f2d-40bd896bc2e4.jpeg)

**Comment by berezovskyi** [comment] 2020-11-26 09:43
"indicate what you expect the result to be." I hope you also understand that I have no idea what the right result was supposed to be because I wanted to learn what a Data rover is.

**Comment by lisp** [comment] 2020-11-26 14:47
metreeca is: https://www.metreeca.com
we had added the link when they were developing their application on our service.
you might write to them if you want to use it.
they may now be doing their own hosting.

**Comment by berezovskyi** [comment] 2020-11-26 14:50
I see, thank you James. Maybe @knoan could help us here (just looking at the https://github.com/metreeca contributors) or otherwise @lisp you could consider removing the link if the functionality will not be restored?

**Comment by berezovskyi** [comment] 2020-11-26 14:52
https://www.metreeca.com/software/ Metreeca Self seems to be the successor to the Data Rover from what I could imagine but I could be wrong.

**Comment by knoan** [comment] 2020-11-26 15:43
The error is likely due to stricter CORS enforcement in recent Safari/Chrome releases. Metreeca/Self (aka Graph Rover) requires CORS support on the target endpoint in order to submit SPARQL queries directly from the browser.

Dydra endpoints currently replies to CORS requests with a wildcard `access-control-allow-origin` header

![Screenshot 2020-11-26 at 16 24 48](https://user-images.githubusercontent.com/6105462/100369251-f8f8f600-3004-11eb-8227-a2057d585505.png)

that is deemed not secure by current CORS policies if credentials are possibly included (as required in order to access private repositories), e.g. on Chrome:

![Screenshot 2020-11-26 at 16 33 40](https://user-images.githubusercontent.com/6105462/100369457-3198cf80-3005-11eb-9e47-84938f00b7a0.png)

The front end isn't able to be more specific in the error message, as security errors are not reported in detail to the application.

Replying with an allowed origin derived from the `origin` request header (`access-control-allow-origin: https://demo.metreeca.com`) would likely resolve the issue.

Details available @ https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

**Comment by lisp** [comment] 2020-11-26 15:59
the dydra.com service runs an older service version.
one which, unfortunately, does not observe the newer meaning of the "*" indicator - especially for preflight requests.
that will be resolved by the next release.

**Comment by lisp** [comment] 2020-11-27 15:48
> Dydra endpoints currently replies to CORS requests with a wildcard access-control-allow-origin header

the application fails with the newer release as well.
it sends no preflight request.
there is just a single request

    POST /cldwalker/knowledge-graph-activities/sparql

which succeeds.  
the request response combinations for three expected preflight variants are enclosed as [20201127-public-61.txt](https://github.com/dydra/support/files/5609283/20201127-public-61.txt) :
- no authentication
- authentication without origin
- authentication with origin

**Comment by knoan** [comment] 2020-11-30 09:39
https://dydra.com/cldwalker/knowledge-graph-activities/sparql is still replying with a wildcard `access-control-allow-origin` header:

![Screenshot 2020-11-30 at 10 22 38](https://user-images.githubusercontent.com/6105462/100591482-20e2a500-32f6-11eb-8e8d-a28730acdc63.png)

No pre-flight request is performed as the app is issuing a `simple` request (see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios): the process is completely under browser control.

**Comment by cldwalker** [comment] 2023-01-25 05:44
Hi. I realize this is an old thread but thought I'd mention that I'm also seeing the same wildcard response that @knoan saw for a new dydra endpoint I tried this on - http://apps.metreeca.it/rover/#endpoint=https://dydra.com/cldwalker/logseq-docs/sparql 

<img width="677" alt="Screen Shot 2023-01-25 at 12 40 41 AM" src="https://user-images.githubusercontent.com/11994/214488953-008ff71d-1096-4585-8ad6-223eeb273ec7.png">

Thanks to both dydra and self as they are great services and hope one day they can work together again

**Comment by lisp** [comment] 2023-01-25 15:39
please be more specific. at the time i understood the issue to be with the -allow-origin value.
the implemented logic distinguishes - in a manner which the rfc indicates to be permissible, between public and private resources.
if you require the response to be specific, the resource must require authentication.

**Closed as completed by lisp** 2023-01-25 15:39 UTC
